name: "PR Checks"
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1

    - name: "install upx on windows"
      if: matrix.os == 'windows-latest'
      run: choco install upx

    - name: "install on macos"
      if: matrix.os == 'macos-latest'
      run: brew install upx

    - name: "install on ubuntu"
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y upx

    - name: "npm install"
      run: npm install

    - name: "npm run build"
      run: npm run build

    - name: "npm run test"
      run: npm run test

    - name: "check for uncommitted changes"
      # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
      if: matrix.os == 'ubuntu-latest'
      run: |
        git diff --exit-code --stat -- . ':!node_modules' \
        || (echo "##[error] found changed files after build. please 'npm run build && npm run format'" \
                 "and check in all changes" \
            && exit 1)
