name: "CI"
on: [pull_request, push]

jobs:
  build: # make sure build/ci work properly
    name: CI on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - run: |
        rm -r node_modules
        npm install
        npm run all

  test: # make sure the action works on a clean machine without building
    name: E2E test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Download test file
      run: |
        curl -Ls https://github.com/svenstaro/proxyboi/releases/download/0.1.5/proxyboi-linux-amd64 -o testbinary
        chmod +x testbinary
    - name: Test Action
      uses: ./
      with:
        file: testbinary
        args: --best --lzma
